# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ood', '0002_auto_20170828_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ttr',
            field=models.DateField(default=datetime.datetime(2017, 8, 29, 14, 59, 23, 219972)),
        ),
    ]
