# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ood', '0003_auto_20170829_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ood.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ood.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ood.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ood.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ttr',
            field=models.DateField(default=datetime.datetime(2017, 8, 29, 16, 38, 10, 108192)),
        ),
    ]
