# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ood', '0004_auto_20170829_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ttr',
            field=models.DateField(default=datetime.datetime(2017, 8, 31, 10, 12, 27, 970014)),
        ),
    ]
